### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by zouter** [DeplanckeLab/Live-seq#7]
Checked reproducibility for

- [x] 1-preprocessing
- [x] 2-Liveseq only
- [x] 2.1-Liveseq only plots
- [x] ~2.2-Liveseq only enrichr~ Not needed as per #1 
- [x] 3-scRNAseq only
- [x] 3.1-scRNAsew only plots
- [x] ~3.2-scRNA-seq only enrichr~ Not needed as per #1 (?)
- [x] 4_Liveseq_scRNAseq_integration
- [x] 4.1_integrated_plot.R
- [x] 5_Liveseq_with_LiveCell_imaging.R
- [x] 6_Clustering_and_accuracy.R waiting on #8 
- [x] 7_DE_Clust-vs-Rest.R
- [x] 7_GO_and_EnrichR.R
- [x] 8_preprocessing_ploting.R
- [x] 9_edgeR_ASPCs_NTvsDMIR.R
- [x] 9_edgeR_RAW_NTvsLPS.R
- [x] 9_GO_enrichment_of-Genes-DE-only-in-one-method.R
- [x] 10.1_Downsample_ASPCs.R
- [x] 10.1_Downsample_RAW.R
- [x] 10.2_Comparison_Barplot_ASPCs.R
- [x] 10.2_Comparison_Barplot_RAW.R
